version: '3.7'

services:

  # Reverse proxy with nginx
  # Automatic updator SSL certificate of Let's Encrypt
  https-portal:
    image: steveltn/https-portal:1
    container_name: lovelab-https-portal
    ports:
      - '80:80'
      - '443:443'
    restart: always
    environment:
      DOMAINS: 'lovelab.pw -> http://lovelab-api:3000/, localhost -> http://lovelab-api:3000/'
      STAGE: 'local'
      # STAGE: 'production'
      # FORCE_RENEW: 'true'

  # API app server
  lovelab-api:
    container_name: lovelab-api
    depends_on:
      - lovelab-postgres
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000"
    env_file:
      - .env
    command: ["./wait-for-postgres.sh","npm","start"]

  # Database
  lovelab-postgres:
    image: postgres:11.6-alpine
    container_name: lovelab-postgres
    restart: always
    expose:
      - "5432"
    volumes:
      - ./postgres-init:/docker-entrypoint-initdb.d:ro
    hostname: $POSTGRES_HOST
    user: $POSTGRES_USER
