version: '3.7'

services:
  lovelab-api:
    env_file:
      - .env.jest
    command: ["./wait-for-postgres.sh","npm","test"]
  lovelab-postgres:
    env_file:
      - .env.jest
  lovelab-batch: 
    env_file:
      - .env.jest
volumes:
  postgres-data-volume:
    name: lovelab-postgres-data-test
