version: '3.7'

services:
  app:
    depends_on:
      - postgresql
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - "0.0.0.0:3000:3000"
    command: ["./wait-for-postgres.sh","npm","start"]
  postgresql:
    image: postgres:11.6-alpine
    container_name: postgresql
    expose:
      - "5432"
    volumes:
      - ./postgres:/docker-entrypoint-initdb.d
        #      - ./postgres-data:/var/lib/pgsql/data/
    env_file:
      - .env
    hostname: $POSTGRES_HOST
    restart: always
    user: $POSTGRES_USER
