version: '3.7'

services:
  lovelab-api:
    env_file:
      - .env
  lovelab-postgres:
    volumes:
      - postgres-data-volume:/var/lib/postgresql/data/
    env_file:
      - .env
volumes:
  postgres-data-volume:
    name: lovelab-postgres-data
    driver: local
