version: '3.7'

services:
  app:
    depends_on:
      - postgresql
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env.test
    ports:
      - "3000"
    command: ["./wait-for-postgres.sh","npm","test"]
  postgresql:
    env_file:
      - .env.test
        #    restart: no
