version: '3.7'

services:

  # Reverse proxy with nginx
  # Automatic updator SSL certificate of Let's Encrypt
  https-portal:
    image: steveltn/https-portal:1
    container_name: lovelab-https-portal
    ports:
      - '80:80'
      - '443:443'
    restart: always
    environment:
      DOMAINS: 'localhost -> http://lovelab-api:3000/'
      STAGE: 'local'
      # STAGE: 'staging'
      # STAGE: 'production'
      # FORCE_RENEW: 'true'
      FORCE_RENEW: 'false'
  lovelab-api:
    env_file:
      - .env
  lovelab-postgres:
    env_file:
      - .env
  lovelab-batch: 
    env_file:
      - .env
