version: 2
jobs:
  deploy:
    machine:
      enabled: true
    steps:
      - checkout
      - add_ssh_keys:
          fingerprints:
            - ${KEY_FINGERPRINT}
      - run:
          name: Deploy Over SSH
          command: |
            ssh ${USER_NAME}@${HOST_NAME} -p ${SSH_PORT} "/home/circleci/deploy.sh"
workflows:
  version: 2
  build-and-deploy:
    jobs:
      - deploy:
          filters:
            branches:
              only: dev/circleci
